baseURL = "https://temperate-designs.github.io"
title = "Temperate Designs"
author = "username"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-K69Z84DP1Y"

# Disqus Comment System
#disqusShortname = ""

[params]
  googlePublisherID = "pub-4328959315579213"

  [params.logo]
    main = "temperate-designs-logo.png"
    alt = "Temperate Designs Logo"

  [params.site]
    name = "Temperate Designs"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fa5 = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "Temperate Designs"
    meta_og_type = "website"
    meta_og_url = "https://temperate-designs.github.io"
    meta_og_image = "red-and-blue-ink-explosion-picjumbo-com-logo.jpg"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 4

  [[menu.main]]
    identifier = "privacy"
    name = "Privacy"
    url = "/privacy/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Privacy"
    url = "/privacy/"
    weight = 2

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/Temperate-Designs"
    weight = 3

  [[menu.footer]]
    name = "Sunflower Dash"
    url = "https://temperate-designs.github.io/sunflower-dash/"
    weight = 4

[build]
  writeStats = true
