baseURL = 'https://temperate-designs.github.io/'
languageCode = 'en-us'
title = 'Temperate Designs'
theme = "ananke"
googleAnalytics = "G-K69Z84DP1Y"
enableRobotsTXT = true

[params]
  site_logo = 'geometric.png'
  author = 'Temperate Designs'
  description = 'Simple yet useful apps.'
  github = 'https://github.com/Temperate-Designs'
  featured_image = 'red-and-blue-ink-explosion-picjumbo-com-logo.jpg'
  recent_posts_number = 2
