version: "3.3"

services:

  site:
    image: docsy/docsy-example
    build:
      context: .
    command: server --source docs --disableFastRender
    ports:
      - "1313:1313"
    volumes:
      - .:/src
